### ISSUE TITLE
Failure showing new created Network

### ISSUE THREAD

**Issue by moxor** [riseuplabs/crabgrass-core#10]
ActionController::RoutingError in Groups/home#show

    Showing app/views/groups/structures/_show_in_sidebar.html.haml where line #6 raised:

    No route matches {:what=>"committees", :updated_at=>1361143475, :action=>"show",   :may_admin=>true, :expires_in=>126031, :authenticity_token=>nil, :lang=>"de",  :_context=>"zukunftssommerwochen", :version=>1, :access=>nil, :path=>nil, :controller=>"groups/home"}

**Comment by elijh** [comment]
I think this is resolved.
