### ISSUE TITLE
Wiki differences showing up instead of page summary

### ISSUE THREAD

**Issue by aliaksandrb** [riseuplabs/crabgrass-core#289]
Hi!

I am not sure what is going on, but currently if you visit https://we.riseup.net/cgdev group, its summary (release notes) flashed and after replaced by mess of wiki diff, header and footer sections.

Its hard to describe, just take a look:
![wiki](https://cloud.githubusercontent.com/assets/526022/8825378/5cda8888-3087-11e5-9dde-05ed284390c4.png)

Ubuntu 14.04.2 LTS x86_64
Google Chrome: Version 43.0.2357.125 (64-bit)

Clearing of browser cache does not help.

**Comment by azul** [comment]
hi @aliaksandrb, 

I think i know what caused this result. Have no idea what triggered it though. Can you still reproduce this?

When a wiki with a new version is loaded it will send an xhr request to fetch the last version and then display the diff. This looks like the last version was not just send with the wiki content but with the whole page content. Therefore the wiki displays the diff between the former full page and the current wiki content.

**Comment by aliaksandrb** [comment]
Hi!
Sorry for a long answer,  I am at some travel journey currently but hope to back soon.

What about issue: still can reproduce it for same group, at my FF 36.0.4.
The note that could help a little is that it is reproducible only when I am logged in.

**Comment by azul** [comment]
We're mostly tracking issues on [gitlab](https://0xacab.org/riseuplabs/crabgrass) these days. So the commit that closed htis issue was actually meant to close this [issue](https://0xacab.org/riseuplabs/crabgrass/issues/289)

However I have not observed this issue in years. So leaving this closed for now. Feel free to reopen.
