### ISSUE TITLE
Creating account when accepting an invite doesn't work

### ISSUE THREAD

**Issue by gagzkrim** [riseuplabs/crabgrass-core#361]
Hey!

So here is how to reproduce the bug :
* Create a group
* In Settings/Permissions, check "Make organisation publicly visible" and "Make members publicly visible" (we didn't check whether the bug still exists when not checking those)
* Go to Members and Send invites, and send an invite to an email address you control
* Visit the provided activation link in another browser (I used chromium --incognito)
* Click "Create account" and fill up the form (I didn't provide an email address)
* When submitting the form, I got forwarded to [this page](https://we.riseup.net/groups/tags/radfem/transfobia/mulheres%20negras+trans/indianara+siqueira/mulheres+trans/radfem/viviane+v%C3%AA), which seems really really weird!!!
* After submitting, the validation code is lost, so I have to click again on the provided link I got by email and there it works

Thanks!

**Comment by azul** [comment]
fixed in #359
